### Listar os carros
GET https://localhost:5001/api/automobile/listar

### Buscar carros
GET https://localhost:5001/api/automobile/buscar/EVK7897

### Cadastrar um carro
POST https://localhost:5001/api/automobile/cadastrar/
Content-Type: application/json

{

  "type": "Carro passeio",
  "models": "Onix - Sedan",
  "brand": "Chevrolet",
  "price_per_day": 260.00,
  "year": "2022",
  "placa": "EVK7897"
    
}

### Deletar um carro
DELETE https://localhost:5001/api/automobile/deletar/1

### Alterar um carro
PATCH https://localhost:5001/api/automobile/alterar
Content-Type: application/json

{
  "automobileId": 1,
  "type": "Carro passeio",
  "models": "Onix - Sedan",
  "brand": "Chevrolet",
  "price_per_day": 260.00,
  "year": "2022",
  "placa": "EVK7897"
    

}