### Listar os clientes
GET https://localhost:5001/api/client/listar

### Buscar um cliente
GET https://localhost:5001/api/client/buscar/12345678912

### Cadastrar um cliente
POST https://localhost:5001/api/client/cadastrar
Content-Type: application/json

{
    "name" : "Leonardo Marques",
    "cpf" : "97765432212",    
    "email" : "leo@gmail.com",
    "cellphone" : "(041)987654321"
}

### Deletar um cliente
DELETE https://localhost:5001/api/client/deletar/1

### Alterar um cliente
PATCH https://localhost:5001/api/client/alterar
Content-Type: application/json

{
    "clienteid" : 2,
    "name" : "nome editado",
    "cpf" : "98765432112",
    "cellphone" : "(041)912345678"
}