### Listar os aluguéis
GET https://localhost:5001/api/rental/listar

### Buscar um aluguel
GET https://localhost:5001/api/rental/buscar/14

### Cadastrar um aluguel
POST https://localhost:5001/api/rental/cadastrar
Content-Type: application/json

{
 
  "clientId": 3,
  "automobileId": 3,
  "total_Price": 3900.00,
  "total_Days": "15",
  "start_Date": "01/10/2022",
  "end_Date": "16/10/2022"
}

### Deletar um aluguel
DELETE https://localhost:5001/api/rental/deletar/14

### Alterar um aluguel
PATCH https://localhost:5001/api/rental/alterar
Content-Type: application/json

{
    "clientId" : 3,
    "automobileId" : 3,
    "Total_Days": "22",
    "total_price" :1000    
}
